
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Laptop
 */

public class MainClassUsingGUI extends javax.swing.JFrame {

    /**
     * Creates new form KendaraanMain
     */
    public MainClassUsingGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TotalJarak2 = new javax.swing.JLabel();
        TotalJarak5 = new javax.swing.JLabel();
        totaljarak3 = new javax.swing.JTextField();
        idkendaraan1 = new javax.swing.JTextField();
        MasukkanID2 = new javax.swing.JLabel();
        MasukkanID5 = new javax.swing.JLabel();
        MasukkanID8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pilihanJenisKendaraan = new javax.swing.JComboBox();
        pilihJenisKendaraan = new javax.swing.JLabel();
        MasukkanID = new javax.swing.JLabel();
        idkendaraan = new javax.swing.JTextField();
        jaraktempuhawal = new javax.swing.JTextField();
        MasukkanJarakTempuhAwal = new javax.swing.JLabel();
        MasukkanJarakTempuh = new javax.swing.JLabel();
        jaraktempuh = new javax.swing.JTextField();
        totaljarak = new javax.swing.JTextField();
        NamaKendaraan = new javax.swing.JLabel();
        TipeKendaraan = new javax.swing.JLabel();
        KapasitasMesin = new javax.swing.JLabel();
        BahanBakar = new javax.swing.JLabel();
        hitungEfisiensi = new javax.swing.JLabel();
        namakendaraan = new javax.swing.JTextField();
        tipekendaraan = new javax.swing.JTextField();
        kapasitasmesin = new javax.swing.JTextField();
        bahanbakar = new javax.swing.JTextField();
        efektivitas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        kesimpulan = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        efektif = new javax.swing.JTextField();
        idkendaraan2 = new javax.swing.JTextField();
        MasukkanID1 = new javax.swing.JLabel();
        MasukkanID3 = new javax.swing.JLabel();
        MasukkanID4 = new javax.swing.JLabel();
        MasukkanID6 = new javax.swing.JLabel();
        MasukkanID7 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        MasukkanID9 = new javax.swing.JLabel();

        TotalJarak2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TotalJarak2.setForeground(new java.awt.Color(255, 255, 255));
        TotalJarak2.setText("Total Jarak                   :");

        TotalJarak5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TotalJarak5.setForeground(new java.awt.Color(255, 255, 255));
        TotalJarak5.setText("Total Jarak                   :");

        MasukkanID2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MasukkanID2.setForeground(new java.awt.Color(255, 255, 255));
        MasukkanID2.setText("---");

        MasukkanID5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MasukkanID5.setForeground(new java.awt.Color(255, 255, 255));
        MasukkanID5.setText("km");

        MasukkanID8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MasukkanID8.setForeground(new java.awt.Color(255, 255, 255));
        MasukkanID8.setText("km");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        pilihanJenisKendaraan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jenis Kendaraan", "Mobil", "Sepeda Motor" }));
        pilihanJenisKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanJenisKendaraanActionPerformed(evt);
            }
        });

        pilihJenisKendaraan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pilihJenisKendaraan.setForeground(new java.awt.Color(255, 255, 255));
        pilihJenisKendaraan.setText("PILIH JENIS KENDARAAN");

        MasukkanID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MasukkanID.setForeground(new java.awt.Color(255, 255, 255));
        MasukkanID.setText("ID Kendaraan               :");

        MasukkanJarakTempuhAwal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MasukkanJarakTempuhAwal.setForeground(new java.awt.Color(255, 255, 255));
        MasukkanJarakTempuhAwal.setText("Jarak Tempuh Awal      :");

        MasukkanJarakTempuh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MasukkanJarakTempuh.setForeground(new java.awt.Color(255, 255, 255));
        MasukkanJarakTempuh.setText("Jarak Tempuh              :");

        NamaKendaraan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NamaKendaraan.setForeground(new java.awt.Color(255, 255, 255));
        NamaKendaraan.setText("Nama Kendaraan         :");

        TipeKendaraan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TipeKendaraan.setForeground(new java.awt.Color(255, 255, 255));
        TipeKendaraan.setText("Tipe Kendaraan            :");

        KapasitasMesin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KapasitasMesin.setForeground(new java.awt.Color(255, 255, 255));
        KapasitasMesin.setText("Kapasitas Mesin            :");

        BahanBakar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BahanBakar.setForeground(new java.awt.Color(255, 255, 255));
        BahanBakar.setText("Bahan Bakar                :");

        hitungEfisiensi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hitungEfisiensi.setForeground(new java.awt.Color(255, 255, 255));
        hitungEfisiensi.setText("Efektivitas                    :");

        jButton1.setText("HITUNG EFEKTIVITAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        kesimpulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kesimpulanActionPerformed(evt);
            }
        });

        jButton2.setText("TOTAL JARAK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        efektif.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        efektif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efektifActionPerformed(evt);
            }
        });

        MasukkanID1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MasukkanID1.setForeground(new java.awt.Color(255, 255, 255));
        MasukkanID1.setText("---");

        MasukkanID3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MasukkanID3.setForeground(new java.awt.Color(255, 255, 255));
        MasukkanID3.setText("km");

        MasukkanID4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MasukkanID4.setForeground(new java.awt.Color(255, 255, 255));
        MasukkanID4.setText("km");

        MasukkanID6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MasukkanID6.setForeground(new java.awt.Color(255, 255, 255));
        MasukkanID6.setText("cc");

        MasukkanID7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MasukkanID7.setForeground(new java.awt.Color(255, 255, 255));
        MasukkanID7.setText("mL");

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        MasukkanID9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MasukkanID9.setForeground(new java.awt.Color(255, 255, 255));
        MasukkanID9.setText("km");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BahanBakar)
                                    .addComponent(KapasitasMesin))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bahanbakar)
                                    .addComponent(kapasitasmesin)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TipeKendaraan)
                                .addGap(23, 23, 23)
                                .addComponent(tipekendaraan))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NamaKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namakendaraan)
                                    .addComponent(totaljarak)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pilihJenisKendaraan)
                                    .addComponent(MasukkanID)
                                    .addComponent(MasukkanJarakTempuhAwal)
                                    .addComponent(MasukkanJarakTempuh))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jaraktempuh, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pilihanJenisKendaraan, 0, 119, Short.MAX_VALUE)
                                    .addComponent(jaraktempuhawal)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(idkendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MasukkanID1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idkendaraan2)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MasukkanID3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MasukkanID4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MasukkanID6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MasukkanID7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MasukkanID9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(efektif, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(kesimpulan, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(hitungEfisiensi)
                            .addGap(23, 23, 23)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(efektivitas)))))
                .addGap(80, 80, 80))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilihanJenisKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilihJenisKendaraan))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MasukkanID)
                    .addComponent(idkendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idkendaraan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MasukkanID1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MasukkanJarakTempuhAwal)
                    .addComponent(jaraktempuhawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MasukkanID3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MasukkanJarakTempuh)
                    .addComponent(jaraktempuh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MasukkanID4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totaljarak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(MasukkanID9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaKendaraan)
                    .addComponent(namakendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipeKendaraan)
                    .addComponent(tipekendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KapasitasMesin)
                    .addComponent(kapasitasmesin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MasukkanID6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BahanBakar)
                    .addComponent(bahanbakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MasukkanID7))
                .addGap(13, 13, 13)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitungEfisiensi)
                    .addComponent(efektivitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kesimpulan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(efektif, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset)
                    .addComponent(exit))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void efektifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efektifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_efektifActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Kendaraan a = new Kendaraan();
        a.jarakTempuhAwal = Float.parseFloat(jaraktempuhawal.getText());
        a.jarakTempuh = Float.parseFloat(jaraktempuh.getText());

        if(Float.parseFloat(jaraktempuh.getText()) <= 0){
            totaljarak.setText("-");
            kesimpulan.setText("Jarak tempuh harus lebih dari 0 km.");
        }
        else if(Float.parseFloat(jaraktempuh.getText()) > 500){
            totaljarak.setText("-");
            kesimpulan.setText("Jarak tempuh harus kurang dari sama dengan 500 km.");
        }
        else if(Float.parseFloat(jaraktempuhawal.getText()) < 0){
            totaljarak.setText("-");
            kesimpulan.setText("Jarak tempuh awal harus lebih dari 0 km.");
        }else {
            totaljarak.setText(String.valueOf(a.totalJarak()));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void kesimpulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kesimpulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kesimpulanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if((pilihanJenisKendaraan.getSelectedIndex()==1)){
            Mobil a = new Mobil();
            a.setJarakTempuh(Float.parseFloat(jaraktempuh.getText()));
            a.setBahanBakar(Float.parseFloat(bahanbakar.getText()));
            float efek = a.efektivitas(a.getJarakTempuh(), a.getBahanBakar());

            if(Float.parseFloat(bahanbakar.getText()) < 0 || Float.parseFloat(bahanbakar.getText()) > 500){
                kesimpulan.setText("Bahan bakar harus lebih dari 0-500 mL.");
                efektivitas.setText("-");
            }
            else if(Float.parseFloat(bahanbakar.getText()) > 0 && Float.parseFloat(bahanbakar.getText()) <= 500){
                if(efek > 0 && efek <= 0.5){
                    efektivitas.setText(String.valueOf(efek));
                    efektif.setText("EFEKTIF");
                }
                else{
                    efektivitas.setText(String.valueOf(efek));
                    efektif.setText("TIDAK EFEKTIF");
                }
            }
        }
        else{
            SepedaMotor a = new SepedaMotor();
            a.setJarakTempuh(Float.parseFloat(jaraktempuh.getText()));
            a.setBahanBakar(Float.parseFloat(bahanbakar.getText()));
            float efek = a.efektivitas(a.getJarakTempuh(), a.getBahanBakar());

            if(Float.parseFloat(bahanbakar.getText()) < 0 || Float.parseFloat(bahanbakar.getText()) > 500){
                kesimpulan.setText("Bahan bakar harus lebih dari 0-500 mL.");
                efektivitas.setText("-");
            }
            else if(Float.parseFloat(bahanbakar.getText()) > 0 && Float.parseFloat(bahanbakar.getText()) <= 500){
                if(efek > 0 && efek <= 0.5){
                    efektivitas.setText(String.valueOf(efek));
                    efektif.setText("EFEKTIF");
                }
                else{
                    efektivitas.setText(String.valueOf(efek));
                    efektif.setText("TIDAK EFEKTIF");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pilihanJenisKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanJenisKendaraanActionPerformed
        // TODO add your handling code here:
        switch(pilihanJenisKendaraan.getSelectedIndex()){
            case 1:
                idkendaraan.setText("01");
            break;
            case 2:
                idkendaraan.setText("02");
                kapasitasmesin.setText("Tidak Ada");
            break;
            default:
            namakendaraan.setText(null);
        }
    }//GEN-LAST:event_pilihanJenisKendaraanActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        idkendaraan.setText(null);
        idkendaraan2.setText(null);
        jaraktempuhawal.setText(null);
        jaraktempuh.setText(null);
        totaljarak.setText(null);
        namakendaraan.setText(null);
        tipekendaraan.setText(null);
        kapasitasmesin.setText(null);
        bahanbakar.setText(null);
        efektivitas.setText(null);
        kesimpulan.setText(null);
        efektif.setText(null);
    }//GEN-LAST:event_resetActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Anda yakin akan keluar?", "WARNING!", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainClassUsingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainClassUsingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainClassUsingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainClassUsingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainClassUsingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BahanBakar;
    private javax.swing.JLabel KapasitasMesin;
    private javax.swing.JLabel MasukkanID;
    private javax.swing.JLabel MasukkanID1;
    private javax.swing.JLabel MasukkanID2;
    private javax.swing.JLabel MasukkanID3;
    private javax.swing.JLabel MasukkanID4;
    private javax.swing.JLabel MasukkanID5;
    private javax.swing.JLabel MasukkanID6;
    private javax.swing.JLabel MasukkanID7;
    private javax.swing.JLabel MasukkanID8;
    private javax.swing.JLabel MasukkanID9;
    private javax.swing.JLabel MasukkanJarakTempuh;
    private javax.swing.JLabel MasukkanJarakTempuhAwal;
    private javax.swing.JLabel NamaKendaraan;
    private javax.swing.JLabel TipeKendaraan;
    private javax.swing.JLabel TotalJarak2;
    private javax.swing.JLabel TotalJarak5;
    private javax.swing.JTextField bahanbakar;
    private javax.swing.JTextField efektif;
    private javax.swing.JTextField efektivitas;
    private javax.swing.JButton exit;
    private javax.swing.JLabel hitungEfisiensi;
    private javax.swing.JTextField idkendaraan;
    private javax.swing.JTextField idkendaraan1;
    private javax.swing.JTextField idkendaraan2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jaraktempuh;
    private javax.swing.JTextField jaraktempuhawal;
    private javax.swing.JTextField kapasitasmesin;
    private javax.swing.JTextField kesimpulan;
    private javax.swing.JTextField namakendaraan;
    private javax.swing.JLabel pilihJenisKendaraan;
    private javax.swing.JComboBox pilihanJenisKendaraan;
    private javax.swing.JButton reset;
    private javax.swing.JTextField tipekendaraan;
    private javax.swing.JTextField totaljarak;
    private javax.swing.JTextField totaljarak3;
    // End of variables declaration//GEN-END:variables
}
